/**
 * @fileoverview Migration for the reservation_expiration_outbox table.
 *
 * This table stores reservation.expired and seat.released events for reliable event publishing
 * via the outbox pattern.
 *
 * Table columns:
 *  - id: UUID, primary key, autogenerated.
 *  - reservation_id: UUID, references reservation.
 *  - seat_id: UUID, references seat.
 *  - session_id: UUID, references session.
 *  - seat_released: Boolean, indicates if the seat was released (default: true).
 *  - reason: String (varchar, 20), reason for expiration (default: 'expired').
 *  - published: Boolean, if the event was published (default: false).
 *  - retry_count: Integer, number of publish retry attempts (default: 0).
 *  - next_retry_at: Timestamp, next retry scheduled time (nullable).
 *  - created_at: Timestamp, creation time (default: now).
 *
 * Constraints:
 *  - PK: id
 *
 * @migration create-reservation-expiration-outbox
 */

import type { MigrationInterface, QueryRunner } from 'typeorm';

/**
 * Migration to create the "reservation_expiration_outbox" table.
 */
export class CreateReservationExpirationOutbox1770760575371 implements MigrationInterface {
  /**
   * Runs the migration to create the "reservation_expiration_outbox" table.
   * @param queryRunner TypeORM QueryRunner used to execute database queries.
   * @returns Promise that resolves when the migration is complete.
   */
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      CREATE TABLE "reservation_expiration_outbox" (
        "id" uuid NOT NULL DEFAULT gen_random_uuid(),
        "reservation_id" uuid NOT NULL,
        "seat_id" uuid NOT NULL,
        "session_id" uuid NOT NULL,
        "seat_released" boolean NOT NULL DEFAULT true,
        "reason" character varying(20) NOT NULL DEFAULT 'expired',
        "published" boolean NOT NULL DEFAULT false,
        "retry_count" integer NOT NULL DEFAULT 0,
        "next_retry_at" TIMESTAMP WITH TIME ZONE NULL,
        "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
        CONSTRAINT "PK_reservation_expiration_outbox" PRIMARY KEY ("id")
      )
    `);
  }

  /**
   * Rolls back the migration, dropping the "reservation_expiration_outbox" table if it exists.
   * @param queryRunner TypeORM QueryRunner used to execute database queries.
   * @returns Promise that resolves when the migration is reverted.
   */
  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `DROP TABLE IF EXISTS "reservation_expiration_outbox"`,
    );
  }
}
