/**
 * @fileoverview Migration to create the sales_outbox table.
 *
 * @migration create-sales-outbox-table
 */
import type { MigrationInterface, QueryRunner } from 'typeorm';

/**
 * Migration to create the "sales_outbox" table.
 *
 * Table columns:
 *  - id: UUID, primary key, autogenerated.
 *  - event: String (varchar), type/name of the event, not null.
 *  - payload: JSONB, the event payload, not null.
 *  - processed: Boolean, indicates if the event has been processed, defaults to false.
 *  - created_at: Timestamp with time zone, creation time, defaults to now.
 * Constraints:
 *  - PK: id
 */
export class CreateSalesOutbox1770760587260 implements MigrationInterface {
  /**
   * Runs the migration to create the "sales_outbox" table.
   * @param queryRunner TypeORM QueryRunner for executing raw queries.
   * @returns Promise that resolves when the table is created.
   */
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      CREATE TABLE "sales_outbox" (
        "id" uuid NOT NULL DEFAULT gen_random_uuid(),
        "event" character varying NOT NULL,
        "payload" jsonb NOT NULL,
        "processed" boolean NOT NULL DEFAULT false,
        "retry_count" integer NOT NULL DEFAULT 0,
        "next_retry_at" TIMESTAMP WITH TIME ZONE NULL,
        "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
        CONSTRAINT "PK_sales_outbox" PRIMARY KEY ("id")
      )
    `);
  }

  /**
   * Reverts the migration by dropping the "sales_outbox" table, if it exists.
   * @param queryRunner TypeORM QueryRunner for executing raw queries.
   * @returns Promise that resolves when the table is dropped.
   */
  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`DROP TABLE IF EXISTS "sales_outbox"`);
  }
}
