/**
 * @fileoverview Migration to create the sessions table.
 *
 * @migration create-sessions-table
 */
import type { MigrationInterface, QueryRunner } from 'typeorm';

/**
 * Migration to create the "sessions" table, which represents individual movie screening sessions.
 *
 * Table columns:
 *  - id: UUID, primary key, autogenerated.
 *  - movie_title: String (varchar 255), required, title of the movie being screened.
 *  - room_name: String (varchar 100), required, name of the room.
 *  - start_time: Timestamp with time zone, required, session start time.
 *  - end_time: Timestamp with time zone, required, session end time.
 *  - ticket_price: Numeric (10,2), required, ticket price for the session.
 *  - status: String (varchar 20), defaults to 'active', session status.
 *  - created_at: Timestamp with time zone, creation timestamp, defaults to now.
 *  - updated_at: Timestamp with time zone, update timestamp, defaults to now.
 * Constraints:
 *  - PK: id
 */
export class CreateSessions1770759950000 implements MigrationInterface {
  /**
   * Runs the migration to create the "sessions" table with its columns and constraints.
   * @param queryRunner TypeORM QueryRunner for executing raw queries.
   */
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      CREATE TABLE IF NOT EXISTS "sessions" (
        "id" uuid NOT NULL DEFAULT gen_random_uuid(),
        "movie_title" character varying(255) NOT NULL,
        "room_name" character varying(100) NOT NULL,
        "start_time" TIMESTAMP WITH TIME ZONE NOT NULL,
        "end_time" TIMESTAMP WITH TIME ZONE NOT NULL,
        "ticket_price" numeric(10,2) NOT NULL,
        "status" character varying(20) NOT NULL DEFAULT 'active',
        "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
        "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
        CONSTRAINT "PK_sessions" PRIMARY KEY ("id")
      )
    `);
  }

  /**
   * Reverts the migration by dropping the "sessions" table, if it exists.
   * @param queryRunner TypeORM QueryRunner for executing raw queries.
   */
  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`DROP TABLE IF EXISTS "sessions"`);
  }
}
