/**
 * @fileoverview Migration to create the reservation_events_outbox table.
 *
 * This table holds events related to reservation creation, used for reliable event publishing
 * via the outbox pattern.
 *
 * Table columns:
 *  - id: UUID, primary key, autogenerated.
 *  - reservation_id: UUID, references the reservation.
 *  - seat_id: UUID, references the seat.
 *  - session_id: UUID, references the session.
 *  - user_id: UUID, references the user.
 *  - expires_at: Timestamp, expiration datetime for reservation.
 *  - published: Boolean, indicates if the event was published, defaults to false.
 *  - retry_count: Integer, tracks publish retry attempts, defaults to 0.
 *  - next_retry_at: Timestamp, nullable, when the next retry is scheduled.
 *  - created_at: Timestamp, creation datetime, defaults to now.
 *
 * Constraints:
 *  - PK: id
 *
 * @migration create-reservation-events-outbox
 */

import type { MigrationInterface, QueryRunner } from 'typeorm';

/**
 * Migration to create the "reservation_events_outbox" table.
 */
export class CreateReservationEventsOutbox1770760575370 implements MigrationInterface {
  /**
   * Runs the migration to create the "reservation_events_outbox" table.
   * @param queryRunner The TypeORM QueryRunner used to execute SQL queries.
   * @returns Promise that resolves when the table is created.
   */
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      CREATE TABLE "reservation_events_outbox" (
        "id" uuid NOT NULL DEFAULT gen_random_uuid(),
        "reservation_id" uuid NOT NULL,
        "seat_id" uuid NOT NULL,
        "session_id" uuid NOT NULL,
        "user_id" uuid NOT NULL,
        "expires_at" TIMESTAMP WITH TIME ZONE NOT NULL,
        "published" boolean NOT NULL DEFAULT false,
        "retry_count" integer NOT NULL DEFAULT 0,
        "next_retry_at" TIMESTAMP WITH TIME ZONE NULL,
        "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
        CONSTRAINT "PK_reservation_events_outbox" PRIMARY KEY ("id")
      )
    `);
  }

  /**
   * Reverts the migration by dropping the "reservation_events_outbox" table, if it exists.
   * @param queryRunner The TypeORM QueryRunner used to execute SQL queries.
   * @returns Promise that resolves when the table is dropped.
   */
  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`DROP TABLE IF EXISTS "reservation_events_outbox"`);
  }
}
