/**
 * @fileoverview Migration to create the seats table.
 *
 * @migration create-seats-table
 */
import type { MigrationInterface, QueryRunner } from 'typeorm';

/**
 * Migration to create the "seats" table for session seating.
 *
 * Table columns:
 *  - id: UUID, primary key, autogenerated.
 *  - session_id: UUID, references the related session (FK to "sessions"), not null.
 *  - label: String (varchar 10), seat label within the session (e.g. "A1"), unique with session_id, not null.
 *  - status: String (varchar 20), seat status (e.g. available, reserved, sold), defaults to 'available'.
 *  - version: Integer, for optimistic locking, defaults to 0.
 *  - created_at: Timestamp with time zone, creation timestamp, defaults to now.
 *  - updated_at: Timestamp with time zone, update timestamp, defaults to now.
 * Constraints:
 *  - PK: id
 *  - FK: session_id -> sessions(id), ON DELETE CASCADE
 *  - Unique: (session_id, label)
 */
export class CreateSeats1770759960000 implements MigrationInterface {
  /**
   * Runs the migration to create the "seats" table and its unique index.
   * @param queryRunner TypeORM QueryRunner for executing raw queries.
   */
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      CREATE TABLE IF NOT EXISTS "seats" (
        "id" uuid NOT NULL DEFAULT gen_random_uuid(),
        "session_id" uuid NOT NULL,
        "label" character varying(10) NOT NULL,
        "status" character varying(20) NOT NULL DEFAULT 'available',
        "version" integer NOT NULL DEFAULT 0,
        "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
        "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
        CONSTRAINT "PK_seats" PRIMARY KEY ("id"),
        CONSTRAINT "FK_seats_session" FOREIGN KEY ("session_id")
          REFERENCES "sessions"("id") ON DELETE CASCADE
      )
    `);

    await queryRunner.query(`
      CREATE UNIQUE INDEX IF NOT EXISTS "idx_seats_session_label"
      ON "seats" ("session_id", "label")
    `);
  }

  /**
   * Reverts the migration by dropping the "seats" table.
   * @param queryRunner TypeORM QueryRunner for executing raw queries.
   */
  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`DROP TABLE IF EXISTS "seats"`);
  }
}
